# Generated by Django 3.2.7 on 2021-12-01 21:10

import coolt_shelf.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_reviews_created', to='coolt_shelf.review')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pic', models.FileField(upload_to=coolt_shelf.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('livro', 'Livro'), ('filme', 'Filme'), ('jogo', 'Jogo'), ('serie', 'Série')], max_length=255)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('synopsis', models.TextField(null=True)),
                ('released', models.DateTimeField()),
                ('img_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_genre_work_genres_created', to='coolt_shelf.genre')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_genre_work_genres_created', to='coolt_shelf.work')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_creator_work_creators_created', to='coolt_shelf.creator')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_creator_work_creators_created', to='coolt_shelf.work')),
            ],
        ),
        migrations.CreateModel(
            name='User_Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_user_followers_created', to='coolt_shelf.user')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_user_followers_created', to='coolt_shelf.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in consume', 'In Consume'), ('consumed', 'Consumed'), ('interest list', 'Interest List'), ('dropped', 'Dropped')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_shelves_created', to='coolt_shelf.user')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_shelves_created', to='coolt_shelf.work')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Não Curti'), (1, 'Curti')], max_length=25)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_like_reviews_likes_created', to='coolt_shelf.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_like_reviews_likes_created', to='coolt_shelf.user')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_reviews_created', to='coolt_shelf.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_reviews_created', to='coolt_shelf.work'),
        ),
    ]
