# Generated by Django 3.2.7 on 2021-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolt_shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='qtd_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='released',
            field=models.DateField(),
        ),
    ]
